# Generated by Django 5.0.1 on 2024-12-10 03:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=250)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('price', models.FloatField()),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
    ]
