# Generated by Django 5.0.1 on 2024-01-29 01:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('product_image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
