# Generated by Django 5.0.1 on 2024-01-29 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
